name: Deploy Static Content to S3

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set wisp.studio environment variables for Vite build.
        run: |
          cp .env.wisp.studio .env

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build static content
        run: npm run build

      - name: Deploy to S3 using AWS CLI
        run: |
          echo "Deploying commit ${{ github.sha }} to S3..."
          aws s3 sync dist s3://wisp.studio/demo --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'